### ISSUE TITLE
xacro fails on ROS_PYTHON_VERSION=3.9

### ISSUE THREAD

**Issue by tmarkmann** [DavidPL1/human_arm#1]
[This line](https://github.com/DavidPL1/human_arm/blob/2bf8a641ba2a53179c3dece2d8382d76e7553704/human_arm_description/launch/upload.launch#L15) evaluates to false if ROS_PYTHON_VERSION is set to a python sub version. This occurs on ROS noetic builds using conda. It's probably better to check for prefix "3".

**Comment by DavidPL1** [comment]
This sounds like an issue on condas end. The purpose of the ROS_PYTHON_VERSION environment variable is to distinguish between the major versions of python. Yet, as it could be simply fixed, I pushed a commit resolving the issue.

Still, this should somehow be reported to the people responsible of conda ros builds, because this probably affects some more ros packages.
